# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rater',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
