# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20160509_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Rater'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Movie'),
        ),
    ]
