# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20160509_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='rater',
        ),
    ]
